#
###################################
# Site wide configuration
####################################
#
title: Sunny the iOS Developer
email: 
description: Sunny Choi
categories: [portfolio]
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: 

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sunny Choi
  avatar: sunny.png
  job: "iOS Developer"
  bio: "Objective-C and Swift"
  email: krazie99@gmail.com
  disqus-shortname:
  twitter: krazie99
  facebook: krazie99
  google:
    plus: krazie99
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: krazie99
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
